import { Geist, Geist_Mono, Urbanist, DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../app/component/navbar";
import Footer from "../app/component/footer"
import { Toaster } from "react-hot-toast";
import './globals.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700', '800'],
  variable: '--font-dm-sans',
});

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-urbanist',
});

export const metadata = {
  title: "Your Multifunctional Virtual Partner | MVP.ai",
  description: "Generated by create next app",
  icons: {
    icon: '/KaiFavicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} ${urbanist.variable} antialiased`}
      >
                <Toaster position="top-center" />

        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
